export default {
    EMAIL_VERIFY: 'EMAIL_VERIFY',
    WALLET_CONNECT: 'WALLET_CONNECT',
    REFERRAL: 'REFERRAL',
    GREETINGS_SUCCESS: 'GREETINGS_SUCCESS',
    PERSONAL: 'PERSONAL',
    PROJECT: 'PROJECT',
    IDENTIFY_DOC: 'IDENTIFY_DOC',
    IDENTIFY_SELFIE: 'IDENTIFY_SELFIE',
    INTERVIEW: 'INTERVIEW',
    SUCCESS: 'SUCCESS',
}